<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <TargetFrameworks>net8.0;net472</TargetFrameworks>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>EsentIsam</RootNamespace>
    <AssemblyName>Esent.Isam</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <FileAlignment>512</FileAlignment>
  </PropertyGroup>
  
  <ItemGroup>
    <Compile Include="*.cs" Exclude="assemblyinfo.cs" />
    <Compile Include="properties\assemblyinfo.cs" />
    <Compile Include="config\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EsentInterop\EsentInterop.csproj">
      <Project>{E929E163-52A0-4AAC-917B-6D7FAF70C45E}</Project>
      <Name>EsentInterop</Name>
    </ProjectReference>
  </ItemGroup>
  
  <!-- To modify your build process, add your task inside one of the targets below and uncomment it. 
       Other similar extension points exist, see Microsoft.Common.targets.
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
  </Target>
  -->
</Project>
